### ISSUE TITLE
Add default value to scribble documentation for tree-fold

### ISSUE THREAD

**Issue by SimonLSchlee** [countvajhula/lazytree#1]
I suggest to change this line https://github.com/countvajhula/lazytree/blob/1ee7e05d00e8d8ac06d9f85a91d59075898704e5/data/lazytree/scribblings/lazytree.scrbl#L189 to `[base any/c undefined]`.

While looking at the examples I was confused that `> (tree-fold .. t)` didn't specify any value for the base parameter.
Looking at the documentation you can't see that base has a default value of `undefined` and can be left out.

I expected something more like: [make-vector](https://docs.racket-lang.org/reference/vectors.html#%28def._%28%28quote._~23~25kernel%29._make-vector%29%29) [src](https://github.com/racket/racket/blob/f9143f04e0122956417e4da0502c0a80ac9e879f/pkgs/racket-doc/scribblings/reference/vectors.scrbl#L35) (seeing brackets around the parameter)

Btw. I am enjoying this library, thank you for creating it!

**Comment by countvajhula** [comment]
I'm glad to hear that, and thank you for reporting the issue. I've committed the fix and it should appear on the main docs in about a day. This also made me realize that these docs still use `..` from `relation` which is considered deprecated in favor of `~`. I will make that change soon as well.
